runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: websocketapp.app

libraries:
- name: ssl
  version: latest
# runtime_config:
  # python_version: 3
  #
# env_variables:
  # FIREBASE_URL: ${FIREBASE_URL}
